name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Add these explicit permissions
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ucc_docs

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Add this line
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./ucc_docs/package-lock.json

      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ucc_docs/build
          force_orphan: true # Add this line